from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QApplication, QWidget, QPushButton, 
QLabel, QVBoxLayout, QHBoxLayout, QMessageBox, 
QGroupBox, QButtonGroup, QRadioButton, QSlider, QCheckBox)
from PyQt5.QtGui import *
from random import randint, shuffle
types = ['экшен', 'приключения', 'РПГ', 'стратегия', 'симулятор', 'спорт', 'головоломка', 'инди']
def choose_type():
    type1 = types[randint(0,len(types)-1)]
    
settings_action = ()
settings_adventure = ()
settings_rpg = ()
settings_strategy = ()
settings_simulation = ()
settings_sport = ()
settings_puzzle = ()
settings_indie = ()

hero_action = ()
hero_adventure = ()
hero_rpg = ()
hero_strategy = ()
hero_simlation = ()
hero_sport = ()
hero_puzzle = ()
hero_indie = ()

app = QApplication([])

button_next = QPushButton('Продолжить выбор')

typebox = QGroupBox('Выбери жанр игры')
type_button1 = QRadioButton()
type_button2 = QRadioButton()
type_button3 = QRadioButton()
type_button4 = QRadioButton()
typegroup = QButtonGroup()
typegroup.addButton(type_button1)
typegroup.addButton(type_button2)
typegroup.addButton(type_button3)
typegroup.addButton(type_button4)
type_line1 = QHBoxLayout()
type_line2 = QVBoxLayout()
type_line3 = QVBoxLayout()
type_line2.addWidget(type_button1)
type_line2.addWidget(type_button2)
type_line3.addWidget(type_button3)
type_line3.addWidget(type_button4)
type_line1.addLayout(type_line2)
type_line1.addLayout(type_line3)
typebox.setLayout(type_line1)

setting = QGroupBox('Выбери сеттинг')
setting_button1 = QRadioButton()
setting_button2 = QRadioButton()
setting_button3 = QRadioButton()
setting_button4 = QRadioButton()
settinggroup = QButtonGroup()
settinggroup.addButton(setting_button1)
settinggroup.addButton(setting_button2)
settinggroup.addButton(setting_button3)
settinggroup.addButton(setting_button4)
setting_line1 = QHBoxLayout()
setting_line2 = QVBoxLayout()
setting_line3 = QVBoxLayout()
setting_line2.addWidget(setting_button1)
setting_line2.addWidget(setting_button2)
setting_line3.addWidget(setting_button3)
setting_line3.addWidget(setting_button4)
setting_line1.addLayout(setting_line2)
setting_line1.addLayout(setting_line3)
setting.setLayout(setting_line1)

difficult = QGroupBox('Выбери сложность')
difficult_line1 = QVBoxLayout()
difficult_line2 = QHBoxLayout()
difficult_line3 = QHBoxLayout()
difficult_slider = QSlider()
difficult_line2.addWidget(difficult_slider)
text_easy = QLabel('Легко')
text_normal = QLabel('Нормально')
text_hard = QLabel('Сложно')
text_expert = QLabel('Эксперт')
text_survivle = QLabel('Режим выживания')
difficult_line3.addWidget(text_easy)
difficult_line3.addWidget(text_normal)
difficult_line3.addWidget(text_hard)
difficult_line3.addWidget(text_expert)
difficult_line3.addWidget(text_survivle)
difficult_line1.addLayout(difficult_line2)
difficult_line1.addLayout(difficult_line3)
difficult.setLayout(difficult_line1)

choose = QGroupBox('Выбери тип игры')
choose_solo = QPushButton('Одиночный режим')
choose_solo.setGeometry(200, 150, 100, 40)
choose_multy = QPushButton('Мультиплеер')
choose_multy.setGeometry(200, 150, 100, 40)
choosegroup = QButtonGroup()
choosegroup.addButton(choose_solo)
choosegroup.addButton(choose_multy)
choose_line1 = QVBoxLayout()
choose_line2 = QHBoxLayout()
choose_line2.addWidget(choose_solo)
choose_line2.addWidget(choose_multy)
choose_line1.addLayout(choose_line2)

text_hero = QLabel('Выбери героя')

layout_line1 = QHBoxLayout()
layout_line2 = QVBoxLayout()
layout_line3 = QVBoxLayout()
layout_line4 = QHBoxLayout()
layout_line2.addWidget(typebox)
layout_line2.addWidget(difficult)
layout_line3.addWidget(setting)
layout_line3.addWidget(choose)
layout_line1.addLayout(layout_line2, stretch=8)
layout_line1.addLayout(layout_line3,stretch=8)

layout_line4.addStretch(1)
layout_line4.addWidget(button_next, stretch=1)
layout_line4.addStretch(1)

main_layout = QVBoxLayout()
main_layout.addLayout(layout_line1, stretch=2)
main_layout.addStretch(1)
main_layout.addLayout(layout_line4, stretch=1)
main_layout.addStretch(1)
main_layout.setSpacing(8)

main = QWidget()
main.setWindowTitle('Генератор идей для разработки видеоигр')
main.resize (1000,500)
main.setLayout(main_layout)


main.show()
app.exec_()
